### ISSUE TITLE
allow to duplicate folders

### ISSUE THREAD

**Issue by capaj** [mrmlnc/vscode-duplicate#19]
currently it just shows and error

**Comment by mrmlnc** [comment]
For future:

  1. Use `fs-extra` instead of `cp-file` (`copy` as promise and without `overwrite` by default).
  2. Allow to duplicate folders.
  3. Also you can add `preserveTimestamps` option from https://github.com/jprichardson/node-fs-extra/blob/master/docs/copy.md#options.
  4. Profit 🎉

**Comment by mrmlnc** [comment]
Please, look at [1.1.0](https://github.com/mrmlnc/vscode-duplicate/releases/tag/1.1.0) 👀
