### ISSUE TITLE
Open file after duplicate

### ISSUE THREAD

**Issue by exdeniz** [mrmlnc/vscode-duplicate#39]
Please add option for open file after duplicate.

**Comment by mrmlnc** [comment]
Good idea! But it's will be work only with files, because we can't open directory.

**Comment by exdeniz** [comment]
For files it will be actual

**Comment by mrmlnc** [comment]
Fixed by #41 and available in `vscode-duplicate@1.2.0`. Thanks @dougshamoo 🌮!
