### ISSUE TITLE
command doesn't work when original file is a "dotfile"

### ISSUE THREAD

**Issue by aoberoi** [mrmlnc/vscode-duplicate#40]
If you try to duplicate a "dotfile", where the name is like `.env.sample`, and the duplicate name you desire is `.env`, the command will fail with message "You can't to copy a file or directory on the same path.".

Here is the problem: Using `path.extname()` will return `''` for "dotfile" file names (e.g. `.env`). Then the command tries to append the original files extension onto the file, so it becomes the same as the original file name (e.g. `.env.sample`). This is not the desired behavior.

I propose that we make this "extension fixing" a configurable setting, so that anyone who depends on this behavior can continue to rely on it, but people who know they don't need it can turn it off.

Small nitpick: the grammar for the error message is incorrect. it should probably read "You can't ~to~ copy a file or directory on the same path".

**Comment by mrmlnc** [comment]
The `duplicate.keepOriginalExtension` option available in [vscode-duplicate@1.2.0](https://github.com/mrmlnc/vscode-duplicate/releases/tag/1.2.0). Please, read release notes 💃
